### ISSUE TITLE
Add github action to sort alphabetical atributes on css

### ISSUE THREAD

**Issue by ImOnlyYisus** [politecnicoDAW-2022/DIW-Proyecto-Gropy#50]
Add github action to sort alphabetical atributes on css:

[npm css-declaration-sorter](https://www.npmjs.com/package/css-declaration-sorter)
- [ ] Modified .github workflow
- [ ] Try to exec before deploy

**Comment by raulwwq0** [comment]
I found a plugin for prettier that allow us to order css when executing prettier and since we execute prettier in every commit I believe it could be a better solution than creating a new action (or at least it is easier to implement).

I already try it and works perfectly, and it uses the package you mention so it is technically the same :D

The plugin -> https://github.com/Siilwyn/prettier-plugin-css-order

**Comment by ImOnlyYisus** [comment]
> I found a plugin for prettier that allow us to order css when executing prettier. Since we execute prettier on every commit due to the hooks I believe it could be a better solution than creating a new action (or at least it is easier to implement).
> 
> I already try it and works perfectly, and it uses the package you mention so it is technically the same :D
> 
> The plugin -> https://github.com/Siilwyn/prettier-plugin-css-order

Perfect, try to implement it 👌🏻👌🏻
